# @file mods.toml
# @spec TOML v0.5.0 (https://github.com/toml-lang/toml)
modLoader="javafml" # forge FML java
loaderVersion="[28,)"
issueTrackerURL="https://github.com/stfwi/rsgauges/issues/"

[[mods]]
modId="rsgauges"
version="${file.jarVersion}"
displayName="Redstone Gauges and Switches"
description="Adds redstone metering gauges, levers, buttons, pressure plates, and all sorts of other sensors and detector switches to the game."
authors="wilechaote"
credits="The Forge smiths, the Modders of the World, Jannis."
updateJSONURL="https://raw.githubusercontent.com/stfwi/rsgauges/develop/meta/update.json"
displayURL="https://github.com/stfwi/rsgauges/"
logoFile="logo.png"

[[dependencies.rsgauges]]
  modId="forge"
  mandatory=true
  versionRange="[30,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.rsgauges]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.15.1]"
  ordering="NONE"
  side="BOTH"
